import type {
  CancelRequest,
  ClassRegistration,
  LessonSlot,
  Member,
  Membership,
  Message,
  PrivateLesson,
  SavedClass,
  ScheduleItem,
  Staff,
  Thread,
  TrainerAssignment,
  UserRole,
} from '@/domain/types';

const BRANCH = 'silver-spring';

/** Seeded week anchored on demo clock date 2026-09-14 (Monday). */
const schedules: ScheduleItem[] = [
  {
    id: 'sched-bodypump-mon',
    branchId: BRANCH,
    category: 'groupEx',
    title: 'BodyPump',
    start: '2026-09-14T10:00:00-04:00',
    end: '2026-09-14T11:00:00-04:00',
    location: 'Studio A',
    instructorName: 'Alex Rivera',
    staffId: 'staff-alex',
    capacity: 20,
    priceCents: 0,
    seniorFriendly: false,
    description: 'Full-body barbell workout for muscular strength and conditioning.',
  },
  {
    id: 'sched-senior-chair-mon',
    branchId: BRANCH,
    category: 'seniors',
    title: 'Gentle Chair Yoga',
    start: '2026-09-14T11:30:00-04:00',
    end: '2026-09-14T12:15:00-04:00',
    location: 'Studio B',
    instructorName: 'Sarah Jenkins',
    staffId: 'staff-sarah',
    capacity: 15,
    priceCents: 0,
    seniorFriendly: true,
    description: 'Gentle seated and supported stretches designed for mobility, balance, and joint relief.',
  },
  {
    id: 'sched-yoga-mon',
    branchId: BRANCH,
    category: 'groupEx',
    title: 'Yoga Flow',
    start: '2026-09-14T18:00:00-04:00',
    end: '2026-09-14T19:00:00-04:00',
    location: 'Studio B',
    instructorName: 'Morgan Lee',
    capacity: 18,
    priceCents: 0,
    description: 'Vinyasa flow yoga connecting breath with movement for all levels.',
  },
  {
    id: 'sched-childwatch-mon',
    branchId: BRANCH,
    category: 'childWatch',
    title: 'Child Watch (Ages 6wks–10yrs)',
    start: '2026-09-14T16:00:00-04:00',
    end: '2026-09-14T20:00:00-04:00',
    location: 'Child Watch Center',
    instructorName: 'YMCA Childcare Staff',
    capacity: 25,
    priceCents: 0,
    description: 'Drop-off childcare for up to 2 hours while parents workout. Included with membership.',
  },
  {
    id: 'sched-cycle-tue',
    branchId: BRANCH,
    category: 'groupEx',
    title: 'Cycle & Spin',
    start: '2026-09-15T06:30:00-04:00',
    end: '2026-09-15T07:15:00-04:00',
    location: 'Cycle Studio',
    instructorName: 'Jamie Chen',
    capacity: 24,
    priceCents: 0,
    description: 'High-energy indoor cycling workout targeting cardio endurance and leg power.',
  },
  {
    id: 'sched-senior-fit-tue',
    branchId: BRANCH,
    category: 'seniors',
    title: 'Fit & Well Seniors',
    start: '2026-09-15T09:30:00-04:00',
    end: '2026-09-15T10:15:00-04:00',
    location: 'Studio A',
    instructorName: 'Sarah Jenkins',
    staffId: 'staff-sarah',
    capacity: 20,
    priceCents: 0,
    seniorFriendly: true,
    description: 'Low-impact cardiovascular conditioning, light hand weights, and stability drills for active older adults.',
  },
  {
    id: 'sched-swim-lesson-tue',
    branchId: BRANCH,
    category: 'swim',
    title: 'Youth Swim Lessons (Stage 2)',
    start: '2026-09-15T16:30:00-04:00',
    end: '2026-09-15T17:15:00-04:00',
    location: 'Teaching Pool',
    instructorName: 'Pat Nguyen',
    capacity: 8,
    priceCents: 2500, // $25.00 extra cost
    seniorFriendly: false,
    description: 'Structured swim lesson focusing on water movement and forward motion without assistance. Specialized paid session.',
  },
  {
    id: 'sched-aqua-wed',
    branchId: BRANCH,
    category: 'swim',
    title: 'Aqua Fit (Water Aerobics)',
    start: '2026-09-16T09:00:00-04:00',
    end: '2026-09-16T10:00:00-04:00',
    location: 'Indoor Pool',
    instructorName: 'Pat Nguyen',
    capacity: 16,
    priceCents: 0,
    seniorFriendly: true,
    description: 'Low-impact, joint-friendly cardio and resistance exercise in water. Included with membership.',
  },
  {
    id: 'sched-senior-arthritis-wed',
    branchId: BRANCH,
    category: 'seniors',
    title: 'Aqua Arthritis Warm Water Therapy',
    start: '2026-09-16T10:30:00-04:00',
    end: '2026-09-16T11:15:00-04:00',
    location: 'Warm Water Pool',
    instructorName: 'Sarah Jenkins',
    staffId: 'staff-sarah',
    capacity: 12,
    priceCents: 0,
    seniorFriendly: true,
    description: 'Gentle soothing warm water class proven to decrease arthritis pain and increase joint mobility.',
  },
  {
    id: 'sched-swim-clinic-wed',
    branchId: BRANCH,
    category: 'swim',
    title: 'Adult Swim Technique & Stroke Coaching',
    start: '2026-09-16T18:00:00-04:00',
    end: '2026-09-16T19:00:00-04:00',
    location: 'Lap Pool (Lanes 1–3)',
    instructorName: 'Coach Marcus Bell',
    capacity: 10,
    priceCents: 3000, // $30.00 extra cost
    seniorFriendly: false,
    description: 'Intensive stroke analysis and breathing mechanics workshop with YMCA certified swim coach.',
  },
  {
    id: 'sched-yoga-thu',
    branchId: BRANCH,
    category: 'groupEx',
    title: 'Yoga Flow',
    start: '2026-09-17T12:00:00-04:00',
    end: '2026-09-17T13:00:00-04:00',
    location: 'Studio B',
    instructorName: 'Morgan Lee',
    capacity: 18,
    priceCents: 0,
    description: 'Mid-day rejuvenation yoga session for strength and flexibility.',
  },
  {
    id: 'sched-senior-parkinsons-thu',
    branchId: BRANCH,
    category: 'seniors',
    title: "Movement for Parkinson's & Balance",
    start: '2026-09-17T14:00:00-04:00',
    end: '2026-09-17T14:45:00-04:00',
    location: 'Wellness Studio',
    instructorName: 'Sarah Jenkins',
    staffId: 'staff-sarah',
    capacity: 14,
    priceCents: 0,
    seniorFriendly: true,
    description: 'Evidence-based functional movement class targeting neuromuscular coordination, gait, and balance.',
  },
  {
    id: 'sched-bodypump-fri',
    branchId: BRANCH,
    category: 'groupEx',
    title: 'BodyPump',
    start: '2026-09-18T17:30:00-04:00',
    end: '2026-09-18T18:30:00-04:00',
    location: 'Studio A',
    instructorName: 'Alex Rivera',
    staffId: 'staff-alex',
    capacity: 20,
    priceCents: 0,
    description: 'Friday evening total body resistance training with energetic soundtrack.',
  },
  {
    id: 'sched-event-social-fri',
    branchId: BRANCH,
    category: 'event',
    title: 'Active Older Adults Coffee & Social',
    start: '2026-09-18T10:00:00-04:00',
    end: '2026-09-18T11:30:00-04:00',
    location: 'Community Room',
    instructorName: 'YMCA Senior Committee',
    capacity: 40,
    priceCents: 0,
    seniorFriendly: true,
    description: 'Complimentary tea, coffee, and lively conversation for our YMCA Silver Spring senior community. Free RSVP.',
  },
  {
    id: 'sched-cycle-sat',
    branchId: BRANCH,
    category: 'groupEx',
    title: 'Cycle & Spin',
    start: '2026-09-19T08:00:00-04:00',
    end: '2026-09-19T08:45:00-04:00',
    location: 'Cycle Studio',
    instructorName: 'Jamie Chen',
    capacity: 24,
    priceCents: 0,
    description: 'Weekend kick-start cycle class.',
  },
  {
    id: 'sched-event-sat',
    branchId: BRANCH,
    category: 'event',
    title: 'Community Open House & Wellness Expo',
    start: '2026-09-19T10:00:00-04:00',
    end: '2026-09-19T14:00:00-04:00',
    location: 'Main Lobby & Gym',
    instructorName: 'YMCA Staff',
    capacity: 100,
    priceCents: 0,
    description: 'Free health screenings, equipment demonstrations, pool tours, and family activities. Included with membership.',
  },
  {
    id: 'sched-event-turkey-sat',
    branchId: BRANCH,
    category: 'event',
    title: 'Turkey Chase Charity 5K Race Entry',
    start: '2026-09-19T08:30:00-04:00',
    end: '2026-09-19T11:00:00-04:00',
    location: 'Silver Spring Outdoor Course',
    instructorName: 'Race Director',
    capacity: 150,
    priceCents: 3500, // $35.00 special event
    isSpecialEvent: true,
    description: 'Official Silver Spring community charity race entry benefitting YMCA youth programs. Special ticketed event.',
  },
  {
    id: 'sched-event-cpr-sun',
    branchId: BRANCH,
    category: 'event',
    title: 'American Red Cross CPR Certification',
    start: '2026-09-20T13:00:00-04:00',
    end: '2026-09-20T16:00:00-04:00',
    location: 'Activity Room 2',
    instructorName: 'Certified ARC Trainer',
    capacity: 12,
    priceCents: 5500, // $55.00 special event
    isSpecialEvent: true,
    description: 'Official certification course in adult & pediatric CPR/AED and First Aid. Includes handbook and certificate.',
  },
];

const lessonSlots: LessonSlot[] = [
  {
    id: 'slot-alex-tue-1000',
    staffId: 'staff-alex',
    branchId: BRANCH,
    start: '2026-09-15T10:00:00-04:00',
    end: '2026-09-15T11:00:00-04:00',
    location: 'Wellness Floor',
  },
  {
    id: 'slot-alex-tue-1400',
    staffId: 'staff-alex',
    branchId: BRANCH,
    start: '2026-09-15T14:00:00-04:00',
    end: '2026-09-15T15:00:00-04:00',
    location: 'Wellness Floor',
  },
  {
    id: 'slot-alex-wed-1100',
    staffId: 'staff-alex',
    branchId: BRANCH,
    start: '2026-09-16T11:00:00-04:00',
    end: '2026-09-16T12:00:00-04:00',
    location: 'Wellness Floor',
  },
  {
    id: 'slot-alex-thu-0900',
    staffId: 'staff-alex',
    branchId: BRANCH,
    start: '2026-09-17T09:00:00-04:00',
    end: '2026-09-17T10:00:00-04:00',
    location: 'Wellness Floor',
  },
  {
    id: 'slot-alex-fri-1000',
    staffId: 'staff-alex',
    branchId: BRANCH,
    start: '2026-09-18T10:00:00-04:00',
    end: '2026-09-18T11:00:00-04:00',
    location: 'Wellness Floor',
  },
  {
    id: 'slot-alex-sat-0900',
    staffId: 'staff-alex',
    branchId: BRANCH,
    start: '2026-09-19T09:00:00-04:00',
    end: '2026-09-19T10:00:00-04:00',
    location: 'Wellness Floor',
  },
  // Sarah Jenkins (Senior Mobility & Aquatics) lesson slots
  {
    id: 'slot-sarah-tue-1100',
    staffId: 'staff-sarah',
    branchId: BRANCH,
    start: '2026-09-15T11:00:00-04:00',
    end: '2026-09-15T12:00:00-04:00',
    location: 'Studio B (Balance & Mobility)',
  },
  {
    id: 'slot-sarah-wed-1400',
    staffId: 'staff-sarah',
    branchId: BRANCH,
    start: '2026-09-16T14:00:00-04:00',
    end: '2026-09-16T15:00:00-04:00',
    location: 'Studio B (Balance & Mobility)',
  },
  {
    id: 'slot-sarah-thu-1000',
    staffId: 'staff-sarah',
    branchId: BRANCH,
    start: '2026-09-17T10:00:00-04:00',
    end: '2026-09-17T11:00:00-04:00',
    location: 'Studio B (Balance & Mobility)',
  },
  {
    id: 'slot-sarah-fri-1300',
    staffId: 'staff-sarah',
    branchId: BRANCH,
    start: '2026-09-18T13:00:00-04:00',
    end: '2026-09-18T14:00:00-04:00',
    location: 'Studio B (Balance & Mobility)',
  },
  // Elena Rostova (Aquatics & Swim) lesson slots
  {
    id: 'slot-elena-mon-1500',
    staffId: 'staff-elena',
    branchId: BRANCH,
    start: '2026-09-14T15:00:00-04:00',
    end: '2026-09-14T16:00:00-04:00',
    location: 'Indoor Lap Pool (Lane 1)',
  },
  {
    id: 'slot-elena-wed-0900',
    staffId: 'staff-elena',
    branchId: BRANCH,
    start: '2026-09-16T09:00:00-04:00',
    end: '2026-09-16T10:00:00-04:00',
    location: 'Indoor Lap Pool (Lane 1)',
  },
  {
    id: 'slot-elena-fri-1500',
    staffId: 'staff-elena',
    branchId: BRANCH,
    start: '2026-09-18T15:00:00-04:00',
    end: '2026-09-18T16:00:00-04:00',
    location: 'Indoor Lap Pool (Lane 1)',
  },
];

export const SEED: {
  members: Member[];
  staff: Staff[];
  memberships: Membership[];
  schedules: ScheduleItem[];
  savedClasses: SavedClass[];
  classRegistrations: ClassRegistration[];
  lessonSlots: LessonSlot[];
  privateLessons: PrivateLesson[];
  assignments: TrainerAssignment[];
  threads: Thread[];
  messages: Message[];
  cancelRequests: CancelRequest[];
  credentials: { email: string; password: string; userId: string; role: UserRole }[];
} = {
  members: [
    {
      id: 'member-jordan',
      name: 'Jordan Hale',
      email: 'jordan@silverspring.ymca',
      phone: '(301) 555-0142',
      address: '123 Georgia Ave, Silver Spring, MD 20910',
      membershipId: '448291',
      homeBranchId: BRANCH,
      type: 'Adult',
      status: 'active',
    },
  ],
  staff: [
    {
      id: 'staff-alex',
      name: 'Alex Rivera',
      email: 'alex@silverspring.ymca',
      roleLabel: 'Personal Wellness Trainer',
      homeBranchId: BRANCH,
    },
    {
      id: 'staff-sarah',
      name: 'Sarah Jenkins',
      email: 'sarah@silverspring.ymca',
      roleLabel: 'Senior Mobility & Aquatics Specialist',
      homeBranchId: BRANCH,
    },
    {
      id: 'staff-elena',
      name: 'Elena Rostova',
      email: 'elena@silverspring.ymca',
      roleLabel: 'Aquatics Director & Swim Coach',
      homeBranchId: BRANCH,
    },
    {
      id: 'staff-desk',
      name: 'Marcus Vance',
      email: 'wellness@silverspring.ymca',
      roleLabel: 'Wellness Desk & Member Services',
      homeBranchId: BRANCH,
    },
  ],
  memberships: [
    {
      memberId: 'member-jordan',
      rateName: 'Adult',
      monthlyAmountCents: 8000,
      nextBillingDate: '2026-10-12',
      paymentBrand: 'Visa',
      paymentLast4: '4242',
    },
  ],
  schedules,
  savedClasses: [],
  classRegistrations: [],
  lessonSlots,
  privateLessons: [],
  assignments: [{ memberId: 'member-jordan', staffId: 'staff-alex' }],
  threads: [
    {
      id: 'thread-jordan-alex',
      memberId: 'member-jordan',
      staffId: 'staff-alex',
    },
    {
      id: 'thread-jordan-sarah',
      memberId: 'member-jordan',
      staffId: 'staff-sarah',
    },
    {
      id: 'thread-jordan-elena',
      memberId: 'member-jordan',
      staffId: 'staff-elena',
    },
    {
      id: 'thread-jordan-desk',
      memberId: 'member-jordan',
      staffId: 'staff-desk',
    },
  ],
  messages: [
    {
      id: 'msg-seed-desk-1',
      threadId: 'thread-jordan-desk',
      fromId: 'staff-desk',
      body: 'Welcome to YMCA Silver Spring! Our wellness staff is here to help with program questions, schedule adjustments, or facility access. How can we support you today?',
      createdAt: '2026-09-14T08:00:00-04:00',
    },
    {
      id: 'msg-seed-sarah-1',
      threadId: 'thread-jordan-sarah',
      fromId: 'staff-sarah',
      body: 'Hi Jordan! Let me know if you want to explore any senior mobility sessions, gentle stretches, or pool workouts this week.',
      createdAt: '2026-09-14T08:30:00-04:00',
    },
  ],
  cancelRequests: [],
  credentials: [
    {
      email: 'jordan@silverspring.ymca',
      password: 'ymca-demo',
      userId: 'member-jordan',
      role: 'member',
    },
    {
      email: 'alex@silverspring.ymca',
      password: 'ymca-demo',
      userId: 'staff-alex',
      role: 'staff',
    },
    {
      email: 'sarah@silverspring.ymca',
      password: 'ymca-demo',
      userId: 'staff-sarah',
      role: 'staff',
    },
    {
      email: 'elena@silverspring.ymca',
      password: 'ymca-demo',
      userId: 'staff-elena',
      role: 'staff',
    },
    {
      email: 'wellness@silverspring.ymca',
      password: 'ymca-demo',
      userId: 'staff-desk',
      role: 'staff',
    },
  ],
};
