import type {
  Announcement,
  AppNotification,
  CancelRequest,
  ClassForumPost,
  ClassRegistration,
  Donation,
  ForumReply,
  ForumTopic,
  LessonSlot,
  Member,
  Membership,
  Message,
  NotificationPreferences,
  PrivateLesson,
  SavedClass,
  ScheduleItem,
  Staff,
  SupportTicket,
  Thread,
  TrainerAssignment,
  UserRole,
} from '@/domain/types';

const BRANCH = 'silver-spring';

/** Seeded week anchored on demo clock date 2026-09-14 (Monday). */
const schedules: ScheduleItem[] = [
  {
    id: 'sched-bodypump-mon',
    branchId: BRANCH,
    category: 'groupEx',
    title: 'BodyPump',
    start: '2026-09-14T10:00:00-04:00',
    end: '2026-09-14T11:00:00-04:00',
    location: 'Studio A',
    instructorName: 'Alex Rivera',
    staffId: 'staff-alex',
    capacity: 20,
    priceCents: 0,
    seniorFriendly: false,
    description: 'Full-body barbell workout for muscular strength and conditioning.',
  },
  {
    id: 'sched-senior-chair-mon',
    branchId: BRANCH,
    category: 'seniors',
    title: 'Gentle Chair Yoga',
    start: '2026-09-14T11:30:00-04:00',
    end: '2026-09-14T12:15:00-04:00',
    location: 'Studio B',
    instructorName: 'Sarah Jenkins',
    staffId: 'staff-sarah',
    capacity: 15,
    priceCents: 0,
    seniorFriendly: true,
    description: 'Gentle seated and supported stretches designed for mobility, balance, and joint relief.',
  },
  {
    id: 'sched-yoga-mon',
    branchId: BRANCH,
    category: 'groupEx',
    title: 'Yoga Flow',
    start: '2026-09-14T18:00:00-04:00',
    end: '2026-09-14T19:00:00-04:00',
    location: 'Studio B',
    instructorName: 'Morgan Lee',
    capacity: 18,
    priceCents: 0,
    description: 'Vinyasa flow yoga connecting breath with movement for all levels.',
  },
  {
    id: 'sched-childwatch-mon',
    branchId: BRANCH,
    category: 'childWatch',
    title: 'Child Watch (Ages 6wks–10yrs)',
    start: '2026-09-14T16:00:00-04:00',
    end: '2026-09-14T20:00:00-04:00',
    location: 'Child Watch Center',
    instructorName: 'YMCA Childcare Staff',
    capacity: 25,
    priceCents: 0,
    description: 'Drop-off childcare for up to 2 hours while parents workout. Included with membership.',
  },
  {
    id: 'sched-cycle-tue',
    branchId: BRANCH,
    category: 'groupEx',
    title: 'Cycle & Spin',
    start: '2026-09-15T06:30:00-04:00',
    end: '2026-09-15T07:15:00-04:00',
    location: 'Cycle Studio',
    instructorName: 'Jamie Chen',
    capacity: 24,
    priceCents: 0,
    description: 'High-energy indoor cycling workout targeting cardio endurance and leg power.',
  },
  {
    id: 'sched-senior-fit-tue',
    branchId: BRANCH,
    category: 'seniors',
    title: 'Fit & Well Seniors',
    start: '2026-09-15T09:30:00-04:00',
    end: '2026-09-15T10:15:00-04:00',
    location: 'Studio A',
    instructorName: 'Sarah Jenkins',
    staffId: 'staff-sarah',
    capacity: 20,
    priceCents: 0,
    seniorFriendly: true,
    description: 'Low-impact cardiovascular conditioning, light hand weights, and stability drills for active older adults.',
  },
  {
    id: 'sched-swim-lesson-tue',
    branchId: BRANCH,
    category: 'swim',
    title: 'Youth Swim Lessons (Stage 2)',
    start: '2026-09-15T16:30:00-04:00',
    end: '2026-09-15T17:15:00-04:00',
    location: 'Teaching Pool',
    instructorName: 'Pat Nguyen',
    capacity: 8,
    priceCents: 2500, // $25.00 extra cost
    seniorFriendly: false,
    description: 'Structured swim lesson focusing on water movement and forward motion without assistance. Specialized paid session.',
  },
  {
    id: 'sched-aqua-wed',
    branchId: BRANCH,
    category: 'swim',
    title: 'Aqua Fit (Water Aerobics)',
    start: '2026-09-16T09:00:00-04:00',
    end: '2026-09-16T10:00:00-04:00',
    location: 'Indoor Pool',
    instructorName: 'Pat Nguyen',
    capacity: 16,
    priceCents: 0,
    seniorFriendly: true,
    description: 'Low-impact, joint-friendly cardio and resistance exercise in water. Included with membership.',
  },
  {
    id: 'sched-senior-arthritis-wed',
    branchId: BRANCH,
    category: 'seniors',
    title: 'Aqua Arthritis Warm Water Therapy',
    start: '2026-09-16T10:30:00-04:00',
    end: '2026-09-16T11:15:00-04:00',
    location: 'Warm Water Pool',
    instructorName: 'Sarah Jenkins',
    staffId: 'staff-sarah',
    capacity: 12,
    priceCents: 0,
    seniorFriendly: true,
    description: 'Gentle soothing warm water class proven to decrease arthritis pain and increase joint mobility.',
  },
  {
    id: 'sched-swim-clinic-wed',
    branchId: BRANCH,
    category: 'swim',
    title: 'Adult Swim Technique & Stroke Coaching',
    start: '2026-09-16T18:00:00-04:00',
    end: '2026-09-16T19:00:00-04:00',
    location: 'Lap Pool (Lanes 1–3)',
    instructorName: 'Coach Marcus Bell',
    capacity: 10,
    priceCents: 3000, // $30.00 extra cost
    seniorFriendly: false,
    description: 'Intensive stroke analysis and breathing mechanics workshop with YMCA certified swim coach.',
  },
  {
    id: 'sched-yoga-thu',
    branchId: BRANCH,
    category: 'groupEx',
    title: 'Yoga Flow',
    start: '2026-09-17T12:00:00-04:00',
    end: '2026-09-17T13:00:00-04:00',
    location: 'Studio B',
    instructorName: 'Morgan Lee',
    capacity: 18,
    priceCents: 0,
    description: 'Mid-day rejuvenation yoga session for strength and flexibility.',
  },
  {
    id: 'sched-senior-parkinsons-thu',
    branchId: BRANCH,
    category: 'seniors',
    title: "Movement for Parkinson's & Balance",
    start: '2026-09-17T14:00:00-04:00',
    end: '2026-09-17T14:45:00-04:00',
    location: 'Wellness Studio',
    instructorName: 'Sarah Jenkins',
    staffId: 'staff-sarah',
    capacity: 14,
    priceCents: 0,
    seniorFriendly: true,
    description: 'Evidence-based functional movement class targeting neuromuscular coordination, gait, and balance.',
  },
  {
    id: 'sched-bodypump-fri',
    branchId: BRANCH,
    category: 'groupEx',
    title: 'BodyPump',
    start: '2026-09-18T17:30:00-04:00',
    end: '2026-09-18T18:30:00-04:00',
    location: 'Studio A',
    instructorName: 'Alex Rivera',
    staffId: 'staff-alex',
    capacity: 20,
    priceCents: 0,
    description: 'Friday evening total body resistance training with energetic soundtrack.',
  },
  {
    id: 'sched-event-social-fri',
    branchId: BRANCH,
    category: 'event',
    title: 'Active Older Adults Coffee & Social',
    start: '2026-09-18T10:00:00-04:00',
    end: '2026-09-18T11:30:00-04:00',
    location: 'Community Room',
    instructorName: 'YMCA Senior Committee',
    capacity: 40,
    priceCents: 0,
    seniorFriendly: true,
    description: 'Complimentary tea, coffee, and lively conversation for our YMCA Silver Spring senior community. Free RSVP.',
  },
  {
    id: 'sched-cycle-sat',
    branchId: BRANCH,
    category: 'groupEx',
    title: 'Cycle & Spin',
    start: '2026-09-19T08:00:00-04:00',
    end: '2026-09-19T08:45:00-04:00',
    location: 'Cycle Studio',
    instructorName: 'Jamie Chen',
    capacity: 24,
    priceCents: 0,
    description: 'Weekend kick-start cycle class.',
  },
  {
    id: 'sched-event-sat',
    branchId: BRANCH,
    category: 'event',
    title: 'Community Open House & Wellness Expo',
    start: '2026-09-19T10:00:00-04:00',
    end: '2026-09-19T14:00:00-04:00',
    location: 'Main Lobby & Gym',
    instructorName: 'YMCA Staff',
    capacity: 100,
    priceCents: 0,
    description: 'Free health screenings, equipment demonstrations, pool tours, and family activities. Included with membership.',
  },
  {
    id: 'sched-event-turkey-sat',
    branchId: BRANCH,
    category: 'event',
    title: 'Turkey Chase Charity 5K Race Entry',
    start: '2026-09-19T08:30:00-04:00',
    end: '2026-09-19T11:00:00-04:00',
    location: 'Silver Spring Outdoor Course',
    instructorName: 'Race Director',
    capacity: 150,
    priceCents: 3500, // $35.00 special event
    isSpecialEvent: true,
    description: 'Official Silver Spring community charity race entry benefitting YMCA youth programs. Special ticketed event.',
  },
  {
    id: 'sched-event-cpr-sun',
    branchId: BRANCH,
    category: 'event',
    title: 'American Red Cross CPR Certification',
    start: '2026-09-20T13:00:00-04:00',
    end: '2026-09-20T16:00:00-04:00',
    location: 'Activity Room 2',
    instructorName: 'Certified ARC Trainer',
    capacity: 12,
    priceCents: 5500, // $55.00 special event
    isSpecialEvent: true,
    description: 'Official certification course in adult & pediatric CPR/AED and First Aid. Includes handbook and certificate.',
  },
];

const lessonSlots: LessonSlot[] = [
  {
    id: 'slot-alex-tue-1000',
    staffId: 'staff-alex',
    branchId: BRANCH,
    start: '2026-09-15T10:00:00-04:00',
    end: '2026-09-15T11:00:00-04:00',
    location: 'Wellness Floor',
  },
  {
    id: 'slot-alex-tue-1400',
    staffId: 'staff-alex',
    branchId: BRANCH,
    start: '2026-09-15T14:00:00-04:00',
    end: '2026-09-15T15:00:00-04:00',
    location: 'Wellness Floor',
  },
  {
    id: 'slot-alex-wed-1100',
    staffId: 'staff-alex',
    branchId: BRANCH,
    start: '2026-09-16T11:00:00-04:00',
    end: '2026-09-16T12:00:00-04:00',
    location: 'Wellness Floor',
  },
  {
    id: 'slot-alex-thu-0900',
    staffId: 'staff-alex',
    branchId: BRANCH,
    start: '2026-09-17T09:00:00-04:00',
    end: '2026-09-17T10:00:00-04:00',
    location: 'Wellness Floor',
  },
  {
    id: 'slot-alex-fri-1000',
    staffId: 'staff-alex',
    branchId: BRANCH,
    start: '2026-09-18T10:00:00-04:00',
    end: '2026-09-18T11:00:00-04:00',
    location: 'Wellness Floor',
  },
  {
    id: 'slot-alex-sat-0900',
    staffId: 'staff-alex',
    branchId: BRANCH,
    start: '2026-09-19T09:00:00-04:00',
    end: '2026-09-19T10:00:00-04:00',
    location: 'Wellness Floor',
  },
  // Sarah Jenkins (Senior Mobility & Aquatics) lesson slots
  {
    id: 'slot-sarah-tue-1100',
    staffId: 'staff-sarah',
    branchId: BRANCH,
    start: '2026-09-15T11:00:00-04:00',
    end: '2026-09-15T12:00:00-04:00',
    location: 'Studio B (Balance & Mobility)',
  },
  {
    id: 'slot-sarah-wed-1400',
    staffId: 'staff-sarah',
    branchId: BRANCH,
    start: '2026-09-16T14:00:00-04:00',
    end: '2026-09-16T15:00:00-04:00',
    location: 'Studio B (Balance & Mobility)',
  },
  {
    id: 'slot-sarah-thu-1000',
    staffId: 'staff-sarah',
    branchId: BRANCH,
    start: '2026-09-17T10:00:00-04:00',
    end: '2026-09-17T11:00:00-04:00',
    location: 'Studio B (Balance & Mobility)',
  },
  {
    id: 'slot-sarah-fri-1300',
    staffId: 'staff-sarah',
    branchId: BRANCH,
    start: '2026-09-18T13:00:00-04:00',
    end: '2026-09-18T14:00:00-04:00',
    location: 'Studio B (Balance & Mobility)',
  },
  // Elena Rostova (Aquatics & Swim) lesson slots
  {
    id: 'slot-elena-mon-1500',
    staffId: 'staff-elena',
    branchId: BRANCH,
    start: '2026-09-14T15:00:00-04:00',
    end: '2026-09-14T16:00:00-04:00',
    location: 'Indoor Lap Pool (Lane 1)',
  },
  {
    id: 'slot-elena-wed-0900',
    staffId: 'staff-elena',
    branchId: BRANCH,
    start: '2026-09-16T09:00:00-04:00',
    end: '2026-09-16T10:00:00-04:00',
    location: 'Indoor Lap Pool (Lane 1)',
  },
  {
    id: 'slot-elena-fri-1500',
    staffId: 'staff-elena',
    branchId: BRANCH,
    start: '2026-09-18T15:00:00-04:00',
    end: '2026-09-18T16:00:00-04:00',
    location: 'Indoor Lap Pool (Lane 1)',
  },
];

export const SEED: {
  members: Member[];
  staff: Staff[];
  memberships: Membership[];
  schedules: ScheduleItem[];
  savedClasses: SavedClass[];
  classRegistrations: ClassRegistration[];
  lessonSlots: LessonSlot[];
  privateLessons: PrivateLesson[];
  assignments: TrainerAssignment[];
  threads: Thread[];
  messages: Message[];
  cancelRequests: CancelRequest[];
  announcements: Announcement[];
  notifications: AppNotification[];
  donations: Donation[];
  credentials: { email: string; password: string; userId: string; role: UserRole }[];
  classForumPosts: ClassForumPost[];
  forumTopics: ForumTopic[];
  forumReplies: ForumReply[];
  notificationPreferences: Record<string, NotificationPreferences>;
  supportTickets: SupportTicket[];
} = {
  members: [
    {
      id: 'member-jordan',
      name: 'Jordan Hale',
      email: 'jordan@silverspring.ymca',
      phone: '(301) 555-0142',
      address: '123 Georgia Ave, Silver Spring, MD 20910',
      membershipId: '448291',
      homeBranchId: BRANCH,
      type: 'Adult',
      status: 'active',
    },
  ],
  staff: [
    {
      id: 'staff-admin',
      name: 'Patricia "Pat" Nguyen',
      email: 'admin@silverspring.ymca',
      roleLabel: 'Executive Branch Director & Staff Admin',
      homeBranchId: BRANCH,
      staffRole: 'staff_admin',
    },
    {
      id: 'staff-itadmin',
      name: 'David Chen',
      email: 'itadmin@silverspring.ymca',
      roleLabel: 'Chief IT Systems & Security Administrator',
      homeBranchId: BRANCH,
      staffRole: 'it_admin',
    },
    {
      id: 'staff-alex',
      name: 'Alex Rivera',
      email: 'alex@silverspring.ymca',
      roleLabel: 'Personal Wellness Trainer',
      homeBranchId: BRANCH,
      staffRole: 'trainer',
    },
    {
      id: 'staff-sarah',
      name: 'Sarah Jenkins',
      email: 'sarah@silverspring.ymca',
      roleLabel: 'Senior Mobility & Aquatics Specialist',
      homeBranchId: BRANCH,
      staffRole: 'trainer',
    },
    {
      id: 'staff-elena',
      name: 'Elena Rostova',
      email: 'elena@silverspring.ymca',
      roleLabel: 'Aquatics Director & Swim Coach',
      homeBranchId: BRANCH,
      staffRole: 'trainer',
    },
    {
      id: 'staff-desk',
      name: 'Marcus Vance',
      email: 'wellness@silverspring.ymca',
      roleLabel: 'Wellness Desk & Member Services',
      homeBranchId: BRANCH,
      staffRole: 'desk',
    },
  ],
  memberships: [
    {
      memberId: 'member-jordan',
      rateName: 'Adult',
      monthlyAmountCents: 8000,
      nextBillingDate: '2026-10-12',
      paymentBrand: 'Visa',
      paymentLast4: '4242',
    },
  ],
  schedules,
  savedClasses: [],
  classRegistrations: [],
  lessonSlots,
  privateLessons: [],
  assignments: [{ memberId: 'member-jordan', staffId: 'staff-alex' }],
  threads: [
    {
      id: 'thread-jordan-alex',
      memberId: 'member-jordan',
      staffId: 'staff-alex',
    },
    {
      id: 'thread-jordan-sarah',
      memberId: 'member-jordan',
      staffId: 'staff-sarah',
    },
    {
      id: 'thread-jordan-elena',
      memberId: 'member-jordan',
      staffId: 'staff-elena',
    },
    {
      id: 'thread-jordan-desk',
      memberId: 'member-jordan',
      staffId: 'staff-desk',
    },
  ],
  messages: [
    {
      id: 'msg-seed-desk-1',
      threadId: 'thread-jordan-desk',
      fromId: 'staff-desk',
      body: 'Welcome to YMCA Silver Spring! Our wellness staff is here to help with program questions, schedule adjustments, or facility access. How can we support you today?',
      createdAt: '2026-09-14T08:00:00-04:00',
    },
    {
      id: 'msg-seed-sarah-1',
      threadId: 'thread-jordan-sarah',
      fromId: 'staff-sarah',
      body: 'Hi Jordan! Let me know if you want to explore any senior mobility sessions, gentle stretches, or pool workouts this week.',
      createdAt: '2026-09-14T08:30:00-04:00',
    },
  ],
  cancelRequests: [],
  announcements: [
    {
      id: 'ann-pool-update',
      branchId: BRANCH,
      title: 'Indoor Lap Pool & Saunas Fully Open',
      body: 'Annual pool maintenance has concluded ahead of schedule. All 6 lap lanes and dry saunas are available for open lap swim, aquatic fitness, and family recreation.',
      category: 'facility',
      priority: 'normal',
      createdAt: '2026-09-14T07:30:00-04:00',
      authorName: 'Pat Nguyen (Aquatics)',
      actionLabel: 'View Pool Hours',
      actionUrl: '/(member)/branch-amenities',
      pinned: true,
    },
    {
      id: 'ann-turkey-chase',
      branchId: BRANCH,
      title: 'Registration Open: Annual Turkey Chase Charity 5K',
      body: 'Join the Silver Spring community for our signature family fun run and competitive 5K. All race proceeds directly fund the YMCA Youth Support Campaign & Open Doors aid.',
      category: 'event',
      priority: 'high',
      createdAt: '2026-09-15T09:00:00-04:00',
      authorName: 'YMCA Events Committee',
      actionLabel: 'View Event & RSVP',
      actionUrl: '/(member)/events',
      pinned: true,
    },
    {
      id: 'ann-swim-lessons',
      branchId: BRANCH,
      title: 'Fall Youth Swim Academy Enrollment',
      body: 'Registration is now live for Stage 1–4 Youth Swim Academy. Members receive priority enrollment and a 20% discount on all 8-week swim modules.',
      category: 'program',
      priority: 'normal',
      createdAt: '2026-09-16T10:15:00-04:00',
      authorName: 'Elena Rostova (Aquatics Director)',
      actionLabel: 'Explore Programs',
      actionUrl: '/(member)/programs',
    },
    {
      id: 'ann-annual-campaign',
      branchId: BRANCH,
      title: '2026 YMCA Annual Giving Campaign Underway',
      body: 'Your tax-deductible gifts ensure no child or senior is turned away from healthy living. Learn how every dollar sponsors youth camp, swim lessons, and senior health.',
      category: 'community',
      priority: 'normal',
      createdAt: '2026-09-16T14:00:00-04:00',
      authorName: 'YMCA Board of Directors',
      actionLabel: 'Support Our Mission',
      actionUrl: '/(member)/donate',
    },
  ],
  notifications: [
    {
      id: 'notif-welcome',
      userId: 'member-jordan',
      title: 'Welcome to YMCA Silver Spring!',
      body: 'Your Adult Membership is active. Scan your barcode pass at the front desk or enjoy open heated pool lap swim.',
      type: 'membership',
      createdAt: '2026-09-14T08:00:00-04:00',
      read: true,
      link: '/(member)/manage-membership',
    },
    {
      id: 'notif-turkey-chase',
      userId: 'member-jordan',
      title: 'Community Event: Turkey Chase Charity 5K',
      body: 'Sign up now for our Saturday charity 5K. Early-bird registration closes this Friday!',
      type: 'event',
      createdAt: '2026-09-15T09:05:00-04:00',
      read: false,
      relatedId: 'sched-event-turkey-sat',
      link: '/(member)/events',
    },
    {
      id: 'notif-pool-alert',
      userId: 'member-jordan',
      title: 'Facility Alert: Pool Maintenance Complete',
      body: 'All indoor lap lanes and warm-water therapy pools are open normal hours.',
      type: 'announcement',
      createdAt: '2026-09-16T08:00:00-04:00',
      read: false,
      link: '/(member)/branch-amenities',
    },
  ],
  donations: [
    {
      id: 'don-seed-1',
      memberId: 'member-jordan',
      donorName: 'Jordan Hale',
      donorEmail: 'jordan@silverspring.ymca',
      amountCents: 5000,
      frequency: 'one-time',
      designation: 'Open Doors Financial Assistance Fund',
      paymentBrand: 'Visa',
      paymentLast4: '4242',
      createdAt: '2026-08-15T14:20:00-04:00',
      taxDeductibleId: '53-0196605',
      receiptNumber: 'YMCA-2026-88192',
    },
  ],
  credentials: [
    {
      email: 'jordan@silverspring.ymca',
      password: 'ymca-demo',
      userId: 'member-jordan',
      role: 'member',
    },
    {
      email: 'admin@silverspring.ymca',
      password: 'ymca-demo',
      userId: 'staff-admin',
      role: 'admin',
    },
    {
      email: 'itadmin@silverspring.ymca',
      password: 'ymca-demo',
      userId: 'staff-itadmin',
      role: 'it_admin',
    },
    {
      email: 'alex@silverspring.ymca',
      password: 'ymca-demo',
      userId: 'staff-alex',
      role: 'trainer',
    },
    {
      email: 'sarah@silverspring.ymca',
      password: 'ymca-demo',
      userId: 'staff-sarah',
      role: 'trainer',
    },
    {
      email: 'elena@silverspring.ymca',
      password: 'ymca-demo',
      userId: 'staff-elena',
      role: 'trainer',
    },
    {
      email: 'wellness@silverspring.ymca',
      password: 'ymca-demo',
      userId: 'staff-desk',
      role: 'staff',
    },
  ],
  classForumPosts: [
    {
      id: 'cfp-yoga-1',
      classId: 'sched-bodypump-mon',
      authorId: 'staff-alex',
      authorName: 'Alex Rivera',
      authorRole: 'trainer',
      content: 'Welcome everyone to Monday BodyPump! Please arrive 5 minutes early to set up your barbell plates and bench height.',
      createdAt: '2026-09-14T08:30:00-04:00',
      pinned: true,
    },
    {
      id: 'cfp-yoga-2',
      classId: 'sched-bodypump-mon',
      authorId: 'member-jordan',
      authorName: 'Jordan Hale',
      authorRole: 'member',
      content: 'Looking forward to it! Are the lighter 2.5lb plates available in the studio?',
      createdAt: '2026-09-14T08:45:00-04:00',
      pinned: false,
    },
    {
      id: 'cfp-yoga-3',
      classId: 'sched-bodypump-mon',
      authorId: 'staff-alex',
      authorName: 'Alex Rivera',
      authorRole: 'trainer',
      content: 'Yes! We have plenty of 2.5lb and 5lb plates on the racks right next to the instructor platform.',
      createdAt: '2026-09-14T08:50:00-04:00',
      pinned: false,
    },
    {
      id: 'cfp-yoga-4',
      classId: 'sched-bodypump-mon',
      authorId: 'staff-itadmin',
      authorName: 'David Chen',
      authorRole: 'it_admin',
      content: 'Studio sound and wireless microphone check passed this morning. Have a great session!',
      createdAt: '2026-09-14T09:00:00-04:00',
      pinned: false,
    },
  ],
  forumTopics: [
    {
      id: 'topic-welcome',
      title: 'Welcome to the YMCA Silver Spring Community Forum! 🏛️',
      content: 'Welcome everyone to our official community discussion space! Here you can share workout milestones, coordinate group meetups, exchange fitness & nutrition tips, and ask our team questions directly by tagging @Staff or specific trainers. Let us keep conversations respectful, supportive, and community-minded!',
      category: 'general',
      authorId: 'staff-admin',
      authorName: 'Patricia "Pat" Nguyen',
      authorRole: 'staff_admin',
      authorAvatarUrl: 'https://images.unsplash.com/avatar-pat.jpg',
      pinned: true,
      likes: 18,
      likedBy: ['member-jordan', 'staff-alex'],
      replyCount: 2,
      hasStaffReply: true,
      createdAt: '2026-09-12T09:00:00-04:00',
      updatedAt: '2026-09-12T10:15:00-04:00',
    },
    {
      id: 'topic-pool-winter',
      title: '@Marcus Vance Will the heated outdoor pool remain open through October? 🏊',
      content: 'Hi everyone and @Marcus Vance, heard rumors that the outdoor 25m heated pool might stay open later into the fall this year with the new thermal covers. Can someone on the aquatics/desk team confirm the schedule?',
      category: 'swim',
      authorId: 'member-jordan',
      authorName: 'Jordan Hale',
      authorRole: 'member',
      pinned: false,
      likes: 9,
      likedBy: ['member-jordan'],
      replyCount: 2,
      mentionedStaffIds: ['staff-desk'],
      mentionedStaffNames: ['Marcus Vance (Front Desk)'],
      hasStaffReply: true,
      createdAt: '2026-09-14T11:20:00-04:00',
      updatedAt: '2026-09-14T12:05:00-04:00',
    },
    {
      id: 'topic-squat-warmup',
      title: '@Alex Rivera Best warm-up drills before heavy barbell squats? 🏋️',
      content: 'Hey @Alex Rivera, I have been dealing with tight hip flexors during my morning leg sessions. What are your recommended dynamic stretches and warmup sets before getting into working weight?',
      category: 'fitness',
      authorId: 'member-jordan',
      authorName: 'Jordan Hale',
      authorRole: 'member',
      pinned: false,
      likes: 12,
      likedBy: [],
      replyCount: 1,
      mentionedStaffIds: ['staff-alex'],
      mentionedStaffNames: ['Alex Rivera (Trainer)'],
      hasStaffReply: true,
      createdAt: '2026-09-15T14:10:00-04:00',
      updatedAt: '2026-09-15T15:30:00-04:00',
    },
    {
      id: 'topic-pickleball',
      title: 'Tuesday Morning Intermediate Pickleball Games! 🏓',
      content: 'Looking for 2 more players for intermediate doubles games on the JOOLA indoor courts every Tuesday at 7:30 AM before work. Drop a reply below if you want to join our regular rotation!',
      category: 'community',
      authorId: 'member-jordan',
      authorName: 'Jordan Hale',
      authorRole: 'member',
      pinned: false,
      likes: 14,
      likedBy: ['member-jordan'],
      replyCount: 2,
      hasStaffReply: false,
      createdAt: '2026-09-16T16:45:00-04:00',
      updatedAt: '2026-09-16T17:20:00-04:00',
    },
    {
      id: 'topic-aoa-mobility',
      title: 'Gentle Chair Yoga & Aqua Arthritis classes are life-changing! 💙',
      content: 'Just wanted to give a huge shoutout to @Sarah Jenkins! The Thursday gentle chair yoga has improved my balance and shoulder mobility tremendously. If anyone has joint stiffness, definitely give it a try.',
      category: 'programs',
      authorId: 'member-jordan',
      authorName: 'Jordan Hale',
      authorRole: 'member',
      pinned: false,
      likes: 21,
      likedBy: ['member-jordan'],
      replyCount: 1,
      mentionedStaffIds: ['staff-sarah'],
      mentionedStaffNames: ['Sarah Jenkins (Trainer)'],
      hasStaffReply: true,
      createdAt: '2026-09-17T09:30:00-04:00',
      updatedAt: '2026-09-17T10:15:00-04:00',
    },
  ],
  forumReplies: [
    {
      id: 'freply-welcome-1',
      topicId: 'topic-welcome',
      content: 'Thrilled to have this community space! Looking forward to connecting with fellow members and trainers.',
      authorId: 'member-jordan',
      authorName: 'Jordan Hale',
      authorRole: 'member',
      isStaffReply: false,
      likes: 3,
      likedBy: [],
      createdAt: '2026-09-12T09:40:00-04:00',
    },
    {
      id: 'freply-welcome-2',
      topicId: 'topic-welcome',
      content: 'Our trainer team is active on here daily! Feel free to tag @Alex Rivera or @Sarah Jenkins anytime for exercise form advice or class questions.',
      authorId: 'staff-alex',
      authorName: 'Alex Rivera',
      authorRole: 'trainer',
      authorAvatarUrl: 'https://images.unsplash.com/avatar-alex.jpg',
      isStaffReply: true,
      likes: 7,
      likedBy: ['member-jordan'],
      createdAt: '2026-09-12T10:15:00-04:00',
    },
    {
      id: 'freply-pool-1',
      topicId: 'topic-pool-winter',
      content: 'Great question Jordan! YES, the outdoor 25m lap pool will remain heated to 81°F and open through November 15th weather permitting. The new thermal solar blankets are deployed overnight to keep morning water temps optimal!',
      authorId: 'staff-desk',
      authorName: 'Marcus Vance',
      authorRole: 'desk',
      authorAvatarUrl: 'https://images.unsplash.com/avatar-marcus.jpg',
      isStaffReply: true,
      likes: 8,
      likedBy: ['member-jordan'],
      createdAt: '2026-09-14T11:45:00-04:00',
    },
    {
      id: 'freply-pool-2',
      topicId: 'topic-pool-winter',
      content: 'That is wonderful news Marcus, thank you for confirming!',
      authorId: 'member-jordan',
      authorName: 'Jordan Hale',
      authorRole: 'member',
      isStaffReply: false,
      likes: 2,
      likedBy: [],
      createdAt: '2026-09-14T12:05:00-04:00',
    },
    {
      id: 'freply-squat-1',
      topicId: 'topic-squat-warmup',
      content: 'Hey Jordan! Try this 5-minute routine: 1) 90/90 hip flow for 60 seconds, 2) Worlds Greatest Stretch (5 reps each side), 3) Deep goblet squat hold with light kettlebell for 45 seconds prying knees outward, and 4) Empty barbell warmup: 2 sets of 8 reps with 3-second pause at bottom. Stop by the desk if you want me to check your barbell bar path!',
      authorId: 'staff-alex',
      authorName: 'Alex Rivera',
      authorRole: 'trainer',
      authorAvatarUrl: 'https://images.unsplash.com/avatar-alex.jpg',
      isStaffReply: true,
      likes: 6,
      likedBy: ['member-jordan'],
      createdAt: '2026-09-15T15:30:00-04:00',
    },
    {
      id: 'freply-pb-1',
      topicId: 'topic-pickleball',
      content: 'Count me in! I will bring a fresh tube of Dura Fast 40 balls.',
      authorId: 'member-taylor',
      authorName: 'Taylor Brooks',
      authorRole: 'member',
      isStaffReply: false,
      likes: 3,
      likedBy: ['member-jordan'],
      createdAt: '2026-09-16T17:10:00-04:00',
    },
    {
      id: 'freply-pb-2',
      topicId: 'topic-pickleball',
      content: 'Awesome Taylor, see you on Court 2 at 7:30 AM!',
      authorId: 'member-jordan',
      authorName: 'Jordan Hale',
      authorRole: 'member',
      isStaffReply: false,
      likes: 2,
      likedBy: [],
      createdAt: '2026-09-16T17:20:00-04:00',
    },
    {
      id: 'freply-aoa-1',
      topicId: 'topic-aoa-mobility',
      content: 'Thank you so much Jordan! It brings me so much joy to see everyone progressing and feeling stronger each week.',
      authorId: 'staff-sarah',
      authorName: 'Sarah Jenkins',
      authorRole: 'trainer',
      authorAvatarUrl: 'https://images.unsplash.com/avatar-sarah.jpg',
      isStaffReply: true,
      likes: 5,
      likedBy: ['member-jordan'],
      createdAt: '2026-09-17T10:15:00-04:00',
    },
  ],
  notificationPreferences: {
    'member-jordan': {
      userId: 'member-jordan',
      mentions: true,
      topicReplies: true,
      classForumAlerts: true,
      staffInquiries: false,
      announcements: true,
      events: true,
      directMessages: true,
      emailDigest: 'daily',
      pushEnabled: true,
      inAppBannerEnabled: true,
      quietHoursEnabled: false,
      quietHoursStart: '22:00',
      quietHoursEnd: '07:00',
    },
    'staff-alex': {
      userId: 'staff-alex',
      mentions: true,
      topicReplies: true,
      classForumAlerts: true,
      staffInquiries: true,
      announcements: true,
      events: true,
      directMessages: true,
      emailDigest: 'instant',
      pushEnabled: true,
      inAppBannerEnabled: true,
      quietHoursEnabled: false,
      quietHoursStart: '22:00',
      quietHoursEnd: '06:00',
    },
    'staff-desk': {
      userId: 'staff-desk',
      mentions: true,
      topicReplies: true,
      classForumAlerts: true,
      staffInquiries: true,
      announcements: true,
      events: true,
      directMessages: true,
      emailDigest: 'instant',
      pushEnabled: true,
      inAppBannerEnabled: true,
      quietHoursEnabled: false,
    },
  },
  supportTickets: [
    {
      id: 'ticket-seed-1',
      ticketNumber: 'YMCA-IT-1001',
      userId: 'member-jordan',
      userName: 'Jordan Hale',
      userEmail: 'jordan@silverspring.ymca',
      userRole: 'member',
      type: 'feature_request',
      title: 'Dark Mode support & Widget shortcut for barcode check-in',
      description: 'Would love to have a home screen widget for fast pool check-in without unlocking and navigating the app!',
      category: 'feature_idea',
      priority: 'normal',
      status: 'in_progress',
      threadId: 'thread-jordan-itadmin',
      deviceInfo: 'iOS 18 · Text Scale: Standard',
      createdAt: '2026-09-15T11:30:00-04:00',
      updatedAt: '2026-09-15T12:00:00-04:00',
    },
  ],
};
