import type {
  CancelRequest,
  Member,
  Membership,
  Message,
  SavedClass,
  ScheduleItem,
  Staff,
  Thread,
  TrainerAssignment,
  UserRole,
} from '@/domain/types';

const BRANCH = 'silver-spring';

/** Seeded week anchored on demo clock date 2026-09-14 (Monday). */
const schedules: ScheduleItem[] = [
  {
    id: 'sched-bodypump-mon',
    branchId: BRANCH,
    category: 'groupEx',
    title: 'BodyPump',
    start: '2026-09-14T10:00:00-04:00',
    end: '2026-09-14T11:00:00-04:00',
    location: 'Studio A',
    instructorName: 'Alex Rivera',
    staffId: 'staff-alex',
  },
  {
    id: 'sched-yoga-mon',
    branchId: BRANCH,
    category: 'groupEx',
    title: 'Yoga Flow',
    start: '2026-09-14T18:00:00-04:00',
    end: '2026-09-14T19:00:00-04:00',
    location: 'Studio B',
    instructorName: 'Morgan Lee',
  },
  {
    id: 'sched-cycle-tue',
    branchId: BRANCH,
    category: 'groupEx',
    title: 'Cycle',
    start: '2026-09-15T06:30:00-04:00',
    end: '2026-09-15T07:15:00-04:00',
    location: 'Cycle Studio',
    instructorName: 'Jamie Chen',
  },
  {
    id: 'sched-aqua-wed',
    branchId: BRANCH,
    category: 'swim',
    title: 'Aqua Fit',
    start: '2026-09-17T09:00:00-04:00',
    end: '2026-09-17T10:00:00-04:00',
    location: 'Pool',
    instructorName: 'Pat Nguyen',
  },
  {
    id: 'sched-yoga-thu',
    branchId: BRANCH,
    category: 'groupEx',
    title: 'Yoga Flow',
    start: '2026-09-18T12:00:00-04:00',
    end: '2026-09-18T13:00:00-04:00',
    location: 'Studio B',
    instructorName: 'Morgan Lee',
  },
  {
    id: 'sched-bodypump-fri',
    branchId: BRANCH,
    category: 'groupEx',
    title: 'BodyPump',
    start: '2026-09-19T17:30:00-04:00',
    end: '2026-09-19T18:30:00-04:00',
    location: 'Studio A',
    instructorName: 'Alex Rivera',
    staffId: 'staff-alex',
  },
  {
    id: 'sched-cycle-sat',
    branchId: BRANCH,
    category: 'groupEx',
    title: 'Cycle',
    start: '2026-09-20T08:00:00-04:00',
    end: '2026-09-20T08:45:00-04:00',
    location: 'Cycle Studio',
    instructorName: 'Jamie Chen',
  },
  {
    id: 'sched-childwatch-mon',
    branchId: BRANCH,
    category: 'childWatch',
    title: 'Child Watch',
    start: '2026-09-14T08:00:00-04:00',
    end: '2026-09-14T12:00:00-04:00',
    location: 'Child Watch',
    instructorName: 'Staff',
  },
  {
    id: 'sched-event-sat',
    branchId: BRANCH,
    category: 'event',
    title: 'Community Open House',
    start: '2026-09-20T10:00:00-04:00',
    end: '2026-09-20T14:00:00-04:00',
    location: 'Lobby',
    instructorName: 'YMCA Staff',
  },
];

export const SEED = {
  members: [
    {
      id: 'member-jordan',
      name: 'Jordan Hale',
      email: 'jordan@silverspring.ymca',
      phone: '(301) 555-0142',
      address: '123 Georgia Ave, Silver Spring, MD 20910',
      membershipId: '448291',
      homeBranchId: BRANCH,
      type: 'Adult',
      status: 'active',
    },
  ],
  staff: [
    {
      id: 'staff-alex',
      name: 'Alex Rivera',
      email: 'alex@silverspring.ymca',
      roleLabel: 'Personal Wellness',
      homeBranchId: BRANCH,
    },
  ],
  memberships: [
    {
      memberId: 'member-jordan',
      rateName: 'Adult',
      monthlyAmountCents: 8000,
      nextBillingDate: '2026-10-12',
      paymentBrand: 'Visa',
      paymentLast4: '4242',
    },
  ],
  schedules,
  savedClasses: [],
  assignments: [{ memberId: 'member-jordan', staffId: 'staff-alex' }],
  threads: [
    {
      id: 'thread-jordan-alex',
      memberId: 'member-jordan',
      staffId: 'staff-alex',
    },
  ],
  messages: [],
  cancelRequests: [],
  credentials: [
    {
      email: 'jordan@silverspring.ymca',
      password: 'ymca-demo',
      userId: 'member-jordan',
      role: 'member',
    },
    {
      email: 'alex@silverspring.ymca',
      password: 'ymca-demo',
      userId: 'staff-alex',
      role: 'staff',
    },
  ],
};
